=== SlimShady1414/AdhiCollibraTest/src/Validator/schemas/dataset-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Dataset",
  "$ref": "#/definitions/Dataset",
  "definitions": {
    "Dataset": {
      "type": "object",
      "title": "Dataset",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Defines name of dataset",
          "minLength": 1,
          "maxLength": 125
        },
        "namespace": {
          "type": "string",
          "pattern": "^[a-z0-9]+(?:[.][a-z0-9]+)*$",
          "minLength": 1,
          "maxLength": 117,
          "description": "Defines namespace of dataset",
          "examples": [
            "sap.s4.afc"
          ]
        },
        "version": {
          "type": "string",
          "description": "Version of this dataset\nVersion number of dataset is not off importance at current version, please set it to 1.0.0 for now.\nWe will revise and update.",
          "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
          "examples": [
            "1.0.0"
          ]
        },
        "datasets": {
          "type": "array",
          "description": "Defines dependent datasets of dataset",
          "items": {
            "type": "string",
            "pattern": "^([a-z0-9]+(?:[.][a-z0-9]+)*):(dataset):([a-zA-Z0-9._\\-]+):(v[0-9]+\\.[0-9]+\\.[0-9])$"
          },
          "minItems": 1,
          "examples": [
            [
              "sap.s4.afc:dataset:CostCenter:v1.0.0"
            ]
          ]
        },
        "dataSources": {
          "type": "array",
          "description": "Defines data sources of dataset",
          "items": {
            "type": "string",
            "pattern": "^([a-z0-9]+(?:[.][a-z0-9]+)*):(dataSource):([a-zA-Z0-9._\\-]+):(v[0-9]+\\.[0-9]+\\.[0-9])$",
            "x-stability": {
                "add": "minor",
                "remove": "major",
                "change": "major"
            }
          },
          "minItems": 1,
          "examples": [
            [
              "sap.s4.afc:dataSource:CostCenter:v1.0.0"
            ]
          ]
        },
        "transformers": {
          "type": "array",
          "description": "Defines transformers applied to this dataset",
          "items": {
            "type": "string",
            "pattern": "^([a-z0-9]+(?:[.][a-z0-9]+)*):(transformer):([a-zA-Z0-9._\\-]+):(v[0-9]+\\.[0-9]+\\.[0-9])$"
          },
          "minItems": 1,
          "examples": [
            [
              "sap.s4.afc:transformer:S4PluginsTransformer:v1.0.0"
            ]
          ]
        }
      },
      "required": [
        "name",
        "namespace",
        "version",
        "dataSources"
      ]
    }
  }
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/datasets/sap/sf/foundationobjects/OrganizationalStructure_1.0.0.json
{
   "name": "OrganizationalStructure",
   "namespace": "sap.sf.foundationobjects",
   "version": "1.0.0",
   "dataSources": [
      "sap.sf.foundationobjects:dataSource:Businessunit:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Department:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Division:v1.0.0"
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/datasets/sap/sf/foundationobjects/PayStructure_1.0.0.json
{
   "name": "PayStructure",
   "namespace": "sap.sf.foundationobjects",
   "version": "1.0.0",
   "dataSources": [
      "sap.sf.foundationobjects:dataSource:Paygrade:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Payrange:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Payscalearea:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Payscalegroup:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Payscalelevel:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Payscaletype:v1.0.0"
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/datasets/sap/sf/capabilities/WorkforceCapability_1.0.0.json
{
   "name": "WorkforceCapability",
   "namespace": "sap.sf.capabilities",
   "version": "1.0.0",
   "dataSources": [
      "sap.sf.capabilities:dataSource:Library:v1.0.0",
      "sap.sf.capabilities:dataSource:Librarytype:v1.0.0",
      "sap.sf.capabilities:dataSource:Proficiencyset:v1.0.0",
      "sap.sf.capabilities:dataSource:Tag:v1.0.0"
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/datasets/sap/sf/foundationobjects/EnterpriseStructure_1.0.0.json
{
   "name": "EnterpriseStructure",
   "namespace": "sap.sf.foundationobjects",
   "version": "1.0.0",
   "dataSources": [
      "sap.sf.foundationobjects:dataSource:Costcenter:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Legalentity:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Location:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Locationgroup:v1.0.0"
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/datasets/sap/sf/foundationobjects/CommonConfigurationData_1.0.0.json
{
   "name": "CommonConfigurationData",
   "namespace": "sap.sf.foundationobjects",
   "version": "1.0.0",
   "dataSources": [
      "sap.sf.foundationobjects:dataSource:Country:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Currency:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Currencyexchangerate:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Eventreason:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Frequency:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Geozone:v1.0.0",
      "sap.sf.foundationobjects:dataSource:Timezone:v1.0.0"
   ]
}
