=== SlimShady1414/AdhiCollibraTest/src/Validator/schemas/share-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Share",
  "$ref": "#/definitions/Share",
  "definitions": {
    "ShareTable": {
      "type": "object",
      "title": "Share table",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the share table"
        },
        "version": {
          "type": "string",
          "description": "Defines version of delta table"
        },
        "medallionLayer": {
          "type": "string",
          "description": "Defines medallion layer of share table",
          "enum": [
            "gold",
            "silver"
          ]
        },
        "cdfEnabled": {
          "type": "boolean",
          "default": true,
          "description": "Enable change data feed"
        }
      },
      "required": [
        "name",
        "version",
        "medallionLayer"
      ]
    },
    "HdlfsSchema": {
      "type": "object",
      "title": "Hdlfs Schema",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the Hdlfs schema"
        },
        "shareTables": {
          "type": "array",
          "description": "Share tables included in this schema",
          "items": {
            "$ref": "#/definitions/ShareTable"
          },
          "minItems": 1
        }
      },
      "required": [
        "name",
        "shareTables"
      ]
    },
    "Share": {
      "type": "object",
      "title": "Share",
      "additionalProperties": false,
      "propertyNames": {
        "pattern": "^[a-z][a-zA-Z0-9_]*$"
      },
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the share",
          "minLength": 1,
          "maxLength": 125,
          "examples": [
            "CostCenter"
          ]
        },
        "namespace": {
          "type": "string",
          "pattern": "^[a-z0-9]+(?:[.][a-z0-9]+)*$",
          "minLength": 1,
          "maxLength": 119,
          "description": "Defines namespace of share",
          "examples": [
            "sap.s4.afc"
          ]
        },
        "title": {
          "type": "string",
          "description": "Human-readable title.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks.\nIf not provided, it will be inherited from data product.",
          "minLength": 1,
          "maxLength": 255,
          "examples": [
            "Process Request for Quotation"
          ]
        },
        "shortDescription": {
          "type": "string",
          "description": "Plain text short description.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks.\nIf not provided, it will be inherited from data product.",
          "minLength": 1,
          "maxLength": 255,
          "examples": [
            "This service enables you to create Request for Quotation (RFQ) through an API call."
          ]
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "description": "Full description, notated in [CommonMark](https://spec.commonmark.org/) (Markdown).\n\nThe description SHOULD not be excessive in length and is not meant to provide full documentation.\nDetailed documentation SHOULD be attached as (typed) links.\nIf not provided, it will be inherited from data product.",
          "examples": [
            "This service enables you to create Request for Quotation (RFQ)\nthrough an API call from a source system outside SAP S/4HANA Cloud\nor SAP S/4HANA on-Premise. Furthermore, the service enables you to\nread existing Request for Quotation data from the SAP S/4HANA Cloud\nor SAP S/4HANA on-Premise.\n"
          ]
        },
        "version": {
          "type": "string",
          "description": "The complete [SemVer](https://semver.org/) version string.\n\nIt MUST follow the [Semantic Versioning 2.0.0](https://semver.org/) standard.\nIt SHOULD be changed if the ORD information or referenced resource definitions changed.\nIt SHOULD express minor and patch changes that don't lead to incompatible changes.\n\nWhen the `version` major version changes, the [ORD ID](#ord-id) `<majorVersion>` fragment MUST be updated to be identical.\nIn case that a resource definition file also contains a version number (e.g. [OpenAPI `info`.`version`](https://swagger.io/specification/#info-object)), it MUST be equal with the resource `version` to avoid inconsistencies.\n\nThe general [Version and Lifecycle](../index.md#version-and-lifecycle) flow MUST be followed.\n\nNote: A change is only relevant for a version increment, if it affects the ORD resource or ORD taxonomy directly.\nFor example: If a resource within a `Package` changes, but the package itself did not, the package version does not need to be incremented.",
          "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
          "examples": [
            "1.2.3",
            "1.0.0-alpha.1"
          ]
        },
        "isRuntimeExtensible": {
          "type": "boolean",
          "description": "Indicates if the share definition can be extended at runtime\n\nIf set to true, then LOBs can provide dynamic share definitions at runtime to extend the static version of the definitions, for example to add more tables to share.",
          "default": false
        },
        "hdlfsSchemas": {
          "type": "array",
          "description": "Hdlfs schemas included in this share",
          "items": {
            "$ref": "#/definitions/HdlfsSchema"
          },
          "minItems": 1
        },
        "extensible": {
          "type": "object",
          "title": "extensible",
          "additionalProperties": false,
          "properties": {
            "supported": {
              "type": "string",
              "enum": [
                "no",
                "manual",
                "automatic"
              ]
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "supported"
          ],
          "anyOf": [
            {
              "properties": {
                "supported": {
                  "const": "manual"
                }
              },
              "required": [
                "description"
              ]
            },
            {
              "properties": {
                "supported": {
                  "const": "automatic"
                }
              },
              "required": [
                "description"
              ]
            }
          ]
        }
      },
      "required": [
        "name",
        "namespace",
        "title",
        "shortDescription",
        "description",
        "version",
        "hdlfsSchemas",
        "extensible"
      ]
    }
  }
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/foundationobjects/CompensationStructure_1.0.0.json
{
   "name": "CompensationStructure",
   "namespace": "sap.sf.foundationobjects",
   "title": "CompensationStructure",
   "shortDescription": "Comp structure refers to component of comp information and their definition.",
   "description": "Compensation structure refers to components of compensation information and their definitions.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "CompensationStructure",
         "shareTables": [
            {
               "name": "payComponentGroup_payComponent",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payComponentGroup_payComponentGroupTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payComponentGroup",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payComponentGroup_payComponentGroupTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payComponent_payComponentTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payComponent",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payComponent_payComponentTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/workforce/RelatedPersons_1.0.0.json
{
   "name": "RelatedPersons",
   "namespace": "sap.sf.workforce",
   "title": "RelatedPersons",
   "shortDescription": "A related person represent person related to or financially reliant on employee, such as a spouse or child.",
   "description": "A related person represents persons related to or financially reliant on an employee, such as a spouse or child.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "RelatedPersons",
         "shareTables": [
            {
               "name": "dependent_dependentPersonalDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "dependent_dependentBiographicalDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "dependent_personRelationship",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "dependent",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/foundationobjects/EnterpriseStructure_1.0.0.json
{
   "name": "EnterpriseStructure",
   "namespace": "sap.sf.foundationobjects",
   "title": "EnterpriseStructure",
   "shortDescription": "Ent structure is info about a company structure relevant for employee. It includes data such as legal entity, location group, location, and cost center.",
   "description": "Enterprise structure is information about a company's structure relevant for employees. It includes data such as legal entity, location group, location, and cost center.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "EnterpriseStructure",
         "shareTables": [
            {
               "name": "legalEntity_LegalEntityBOL",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_legalEntityText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntitySVN",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_legalEntityTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityTHA",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityUSA",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityTUN",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityBLR",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityARG",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityRUS",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntitySGP",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntitySAU",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityDEU",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityCAN",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityFRA",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityESP",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "legalEntity_LegalEntityPRY",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "locationGroup",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "locationGroup_locationGroupTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "locationGroup_locationGroupTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "location_legalEntity",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "location_locationTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "location_locationTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "location_addressInformation",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "location",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "location_LegalEntity",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "costCenter_legalEntity",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "costCenter",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "costCenter_costCenterTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "costCenter_costCenterText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/learning/LearningHistory_1.0.0.json
{
   "name": "LearningHistory",
   "namespace": "sap.sf.learning",
   "title": "LearningHistory",
   "shortDescription": "Learning History includes the information of all completions including courses and programs",
   "description": "Learning History includes information of all completions including courses, programs[User Data]",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "LearningHistory",
         "shareTables": [
            {
               "name": "learningCompletion",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/foundationobjects/PayStructure_1.0.0.json
{
   "name": "PayStructure",
   "namespace": "sap.sf.foundationobjects",
   "title": "PayStructure",
   "shortDescription": "Pay structure refer to the payment defn, including pay range, pay grade, and pay scale type.",
   "description": "Pay structure refers to the payment definition, including pay range, pay grade, and pay scale types.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "PayStructure",
         "shareTables": [
            {
               "name": "payScaleType_payScaleTypeText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleType",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleGroup_payScaleGroupText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleGroup",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleArea",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleArea_payScaleAreaText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleLevel_payScaleLevelText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleLevel",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleLevel_PayScalePayComponent",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payScaleLevel_payScaleLevelTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payGrade",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payGrade_payGradeTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payGrade_payGradeTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payRange",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payRange_payRangeTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "payRange_payRangeTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/workforce/Position_1.0.0.json
{
   "name": "Position",
   "namespace": "sap.sf.workforce",
   "title": "Position",
   "shortDescription": "Job position is the smallest unit of the org structure in a certain part of a company and comprises a specific occurrence of a job.",
   "description": "Job position is the smallest unit of the organizational structure in a certain part of a company and comprises a specific occurrence of a job with a fixed combination of tasks, competencies, and responsibilities.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "Position",
         "shareTables": [
            {
               "name": "position",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "position_positionText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "position_PositionMatrixRelationship",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "position_positionTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/capabilities/GrowthPortfolio_1.0.0.json
{
   "name": "GrowthPortfolio",
   "namespace": "sap.sf.capabilities",
   "title": "GrowthPortfolio",
   "shortDescription": "Provides profile data of the employees with Skills and Attributes",
   "description": "This data product provides Profile data of employees with Skills and Attributes",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "GrowthPortfolio",
         "shareTables": [
            {
               "name": "growthPortfolioAttribute",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "growthPortfolioAttribute_assessmentHistory",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/workforce/ContingentManagementData_1.0.0.json
{
   "name": "ContingentManagementData",
   "namespace": "sap.sf.workforce",
   "title": "ContingentManagementData",
   "shortDescription": "Contingent management includes info about contingent workers distributors who are entrusted with the staffing responsibilities in a company.",
   "description": "Contingent management data includes information about contingent workers's distributors who are entrusted with the staffing responsibilities in a company.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "ContingentManagementData",
         "shareTables": [
            {
               "name": "vendorInfo_vendorInfoText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "vendorInfo_vendorInfoTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "vendorInfo",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}
