=== SlimShady1414/AdhiCollibraTest/src/Validator/schemas/share-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Share",
  "$ref": "#/definitions/Share",
  "definitions": {
    "ShareTable": {
      "type": "object",
      "title": "Share table",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the share table"
        },
        "version": {
          "type": "string",
          "description": "Defines version of delta table"
        },
        "medallionLayer": {
          "type": "string",
          "description": "Defines medallion layer of share table",
          "enum": [
            "gold",
            "silver"
          ]
        },
        "cdfEnabled": {
          "type": "boolean",
          "default": true,
          "description": "Enable change data feed"
        }
      },
      "required": [
        "name",
        "version",
        "medallionLayer"
      ]
    },
    "HdlfsSchema": {
      "type": "object",
      "title": "Hdlfs Schema",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the Hdlfs schema"
        },
        "shareTables": {
          "type": "array",
          "description": "Share tables included in this schema",
          "items": {
            "$ref": "#/definitions/ShareTable"
          },
          "minItems": 1
        }
      },
      "required": [
        "name",
        "shareTables"
      ]
    },
    "Share": {
      "type": "object",
      "title": "Share",
      "additionalProperties": false,
      "propertyNames": {
        "pattern": "^[a-z][a-zA-Z0-9_]*$"
      },
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the share",
          "minLength": 1,
          "maxLength": 125,
          "examples": [
            "CostCenter"
          ]
        },
        "namespace": {
          "type": "string",
          "pattern": "^[a-z0-9]+(?:[.][a-z0-9]+)*$",
          "minLength": 1,
          "maxLength": 119,
          "description": "Defines namespace of share",
          "examples": [
            "sap.s4.afc"
          ]
        },
        "title": {
          "type": "string",
          "description": "Human-readable title.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks.\nIf not provided, it will be inherited from data product.",
          "minLength": 1,
          "maxLength": 255,
          "examples": [
            "Process Request for Quotation"
          ]
        },
        "shortDescription": {
          "type": "string",
          "description": "Plain text short description.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks.\nIf not provided, it will be inherited from data product.",
          "minLength": 1,
          "maxLength": 255,
          "examples": [
            "This service enables you to create Request for Quotation (RFQ) through an API call."
          ]
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "description": "Full description, notated in [CommonMark](https://spec.commonmark.org/) (Markdown).\n\nThe description SHOULD not be excessive in length and is not meant to provide full documentation.\nDetailed documentation SHOULD be attached as (typed) links.\nIf not provided, it will be inherited from data product.",
          "examples": [
            "This service enables you to create Request for Quotation (RFQ)\nthrough an API call from a source system outside SAP S/4HANA Cloud\nor SAP S/4HANA on-Premise. Furthermore, the service enables you to\nread existing Request for Quotation data from the SAP S/4HANA Cloud\nor SAP S/4HANA on-Premise.\n"
          ]
        },
        "version": {
          "type": "string",
          "description": "The complete [SemVer](https://semver.org/) version string.\n\nIt MUST follow the [Semantic Versioning 2.0.0](https://semver.org/) standard.\nIt SHOULD be changed if the ORD information or referenced resource definitions changed.\nIt SHOULD express minor and patch changes that don't lead to incompatible changes.\n\nWhen the `version` major version changes, the [ORD ID](#ord-id) `<majorVersion>` fragment MUST be updated to be identical.\nIn case that a resource definition file also contains a version number (e.g. [OpenAPI `info`.`version`](https://swagger.io/specification/#info-object)), it MUST be equal with the resource `version` to avoid inconsistencies.\n\nThe general [Version and Lifecycle](../index.md#version-and-lifecycle) flow MUST be followed.\n\nNote: A change is only relevant for a version increment, if it affects the ORD resource or ORD taxonomy directly.\nFor example: If a resource within a `Package` changes, but the package itself did not, the package version does not need to be incremented.",
          "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
          "examples": [
            "1.2.3",
            "1.0.0-alpha.1"
          ]
        },
        "isRuntimeExtensible": {
          "type": "boolean",
          "description": "Indicates if the share definition can be extended at runtime\n\nIf set to true, then LOBs can provide dynamic share definitions at runtime to extend the static version of the definitions, for example to add more tables to share.",
          "default": false
        },
        "hdlfsSchemas": {
          "type": "array",
          "description": "Hdlfs schemas included in this share",
          "items": {
            "$ref": "#/definitions/HdlfsSchema"
          },
          "minItems": 1
        },
        "extensible": {
          "type": "object",
          "title": "extensible",
          "additionalProperties": false,
          "properties": {
            "supported": {
              "type": "string",
              "enum": [
                "no",
                "manual",
                "automatic"
              ]
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "supported"
          ],
          "anyOf": [
            {
              "properties": {
                "supported": {
                  "const": "manual"
                }
              },
              "required": [
                "description"
              ]
            },
            {
              "properties": {
                "supported": {
                  "const": "automatic"
                }
              },
              "required": [
                "description"
              ]
            }
          ]
        }
      },
      "required": [
        "name",
        "namespace",
        "title",
        "shortDescription",
        "description",
        "version",
        "hdlfsSchemas",
        "extensible"
      ]
    }
  }
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/foundationobjects/CommonConfigurationData_1.0.0.json
{
   "name": "CommonConfigurationData",
   "namespace": "sap.sf.foundationobjects",
   "title": "CommonConfigurationData",
   "shortDescription": "Common configuration data is info that can be shared across the company, such as currency, country code, exchange rate, and time zone.",
   "description": "Common configuration data  is information that can be shared across the entire company, such as currencies, country codes, exchange rates, and time zones.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "CommonConfigurationData",
         "shareTables": [
            {
               "name": "currency",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "currency_currencyText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "currency_currencyTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "country",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "country_countryTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "country_countryText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "currencyExchangeRate_currencyExchangeRateText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "currencyExchangeRate",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "currencyExchangeRate_currencyExchangeRateTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "timeZone_timeZoneText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "timeZone",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "timeZone_timeZoneTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "geoZone",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "geoZone_geoZoneTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "geoZone_geoZoneTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "frequency_frequencyText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "frequency",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "eventReason",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "eventReason_eventReasonTimeslice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "eventReason_eventReasonTimesliceText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/recruiting/JobApplication_1.0.0.json
{
   "name": "JobApplication",
   "namespace": "sap.sf.recruiting",
   "title": "JobApplication",
   "shortDescription": "Data product that helps track and manage a candidate's application, monitoring progress, job details, and skills to streamline evaluation and hiring.",
   "description": "Tracks and manages a candidate's application, monitoring progress, job details, and skills to streamline evaluation and hiring.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "JobApplication",
         "shareTables": [
            {
               "name": "jobApplication",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_currencyData",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_questionResponse",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_comment",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_assessment",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_onboardingInformation",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_backgroundCheck",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_courses",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_certificates",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_mobility",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_languages",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_education",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_insideWorkExperience",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_outsideWorkExperience",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_statusAudit",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_skillProfile",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobApplication_skill",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/capabilities/WorkforceCapability_1.0.0.json
{
   "name": "WorkforceCapability",
   "namespace": "sap.sf.capabilities",
   "title": "WorkforceCapability",
   "shortDescription": "This Data Product includes Attribute, Attribute Type, Proficiency Set, and Tag).",
   "description": "This Data Product in the Talent Intelligence Hub includes Attribute (a specific skill or other Attributes), Attribute Type (type of the attribute), Proficiency Set (levels of expertise), and Tag (contextual keywords for filtering and search)",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "WorkforceCapability",
         "shareTables": [
            {
               "name": "library",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "library_source",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "library_libraryTypeRef",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "library_libraryText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "library_tag",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "libraryType",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "libraryType_libraryTypeText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "proficiencySet",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "proficiencySet_proficiencySetText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "proficiencySet_proficiencyLevel",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "proficiencySet_proficiencyLevelText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "tag",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "tag_tagText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/learning/Classification_1.0.0.json
{
   "name": "Classification",
   "namespace": "sap.sf.learning",
   "title": "Classification",
   "shortDescription": "Contains reference data that is required in Learning.",
   "description": "Reference Data required in Learning",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "Classification",
         "shareTables": [
            {
               "name": "classification_classificationText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "classification",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/derived/PersonInfo/output/sap/sf/analytics/share/PersonInfo_1.0.0.json
{
    "name": "PersonInfo",
    "namespace": "sap.sf.analytics",
    "title": "Person Info",
    "shortDescription": "PersonInfo short description",
    "description": "PersonInfo description",
    "version": "1.0.0",
    "extensible": {
        "supported": "automatic",
        "description": "API can be extended by custom fields on the following business contexts"
    },
    "hdlfsSchemas": [
        {
            "name": "PersonInfo",
            "shareTables": [
                {
                    "name": "PersonInfo",
                    "version": "1.0.0",
                    "medallionLayer": "gold"
                }
            ]
        }
    ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/workforce/Compensation_1.0.0.json
{
   "name": "Compensation",
   "namespace": "sap.sf.workforce",
   "title": "Compensation",
   "shortDescription": "Data Product for Compensation info of assignment includes compensation details and one-time payments.",
   "description": "Data Product that contains Compensation information of assignment includes compensation details and one-time payments.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "Compensation",
         "shareTables": [
            {
               "name": "oneTimePayment_oneTimePaymentDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "oneTimePayment",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "compensationInfo",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "compensationInfo_compDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "compensationInfo_recurringPayComponent",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "compensationInfo_targetPayComponent",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/learning/Program_1.0.0.json
{
   "name": "Program",
   "namespace": "sap.sf.learning",
   "title": "Program",
   "shortDescription": "Includes all information for a Program. Delivery Date assumes that all the dependencies are in place.",
   "description": "Includes all information for a Program[Entity].Delivery Date assumes that all dependencies are in place. If this is not the case then Delivery Qtr will be re-determined",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "Program",
         "shareTables": [
            {
               "name": "program",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "program_capabilityRating",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "program_learningItemText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "program_categories",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/learning/CompletionStatus_1.0.0.json
{
   "name": "CompletionStatus",
   "namespace": "sap.sf.learning",
   "title": "CompletionStatus",
   "shortDescription": "Reference data that is required in Learning.",
   "description": "Reference Data required in Learning.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "CompletionStatus",
         "shareTables": [
            {
               "name": "completionStatus_completionStatusText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "completionStatus",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}
