=== SlimShady1414/AdhiCollibraTest/src/Validator/schemas/share-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Share",
  "$ref": "#/definitions/Share",
  "definitions": {
    "ShareTable": {
      "type": "object",
      "title": "Share table",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the share table"
        },
        "version": {
          "type": "string",
          "description": "Defines version of delta table"
        },
        "medallionLayer": {
          "type": "string",
          "description": "Defines medallion layer of share table",
          "enum": [
            "gold",
            "silver"
          ]
        },
        "cdfEnabled": {
          "type": "boolean",
          "default": true,
          "description": "Enable change data feed"
        }
      },
      "required": [
        "name",
        "version",
        "medallionLayer"
      ]
    },
    "HdlfsSchema": {
      "type": "object",
      "title": "Hdlfs Schema",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the Hdlfs schema"
        },
        "shareTables": {
          "type": "array",
          "description": "Share tables included in this schema",
          "items": {
            "$ref": "#/definitions/ShareTable"
          },
          "minItems": 1
        }
      },
      "required": [
        "name",
        "shareTables"
      ]
    },
    "Share": {
      "type": "object",
      "title": "Share",
      "additionalProperties": false,
      "propertyNames": {
        "pattern": "^[a-z][a-zA-Z0-9_]*$"
      },
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the share",
          "minLength": 1,
          "maxLength": 125,
          "examples": [
            "CostCenter"
          ]
        },
        "namespace": {
          "type": "string",
          "pattern": "^[a-z0-9]+(?:[.][a-z0-9]+)*$",
          "minLength": 1,
          "maxLength": 119,
          "description": "Defines namespace of share",
          "examples": [
            "sap.s4.afc"
          ]
        },
        "title": {
          "type": "string",
          "description": "Human-readable title.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks.\nIf not provided, it will be inherited from data product.",
          "minLength": 1,
          "maxLength": 255,
          "examples": [
            "Process Request for Quotation"
          ]
        },
        "shortDescription": {
          "type": "string",
          "description": "Plain text short description.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks.\nIf not provided, it will be inherited from data product.",
          "minLength": 1,
          "maxLength": 255,
          "examples": [
            "This service enables you to create Request for Quotation (RFQ) through an API call."
          ]
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "description": "Full description, notated in [CommonMark](https://spec.commonmark.org/) (Markdown).\n\nThe description SHOULD not be excessive in length and is not meant to provide full documentation.\nDetailed documentation SHOULD be attached as (typed) links.\nIf not provided, it will be inherited from data product.",
          "examples": [
            "This service enables you to create Request for Quotation (RFQ)\nthrough an API call from a source system outside SAP S/4HANA Cloud\nor SAP S/4HANA on-Premise. Furthermore, the service enables you to\nread existing Request for Quotation data from the SAP S/4HANA Cloud\nor SAP S/4HANA on-Premise.\n"
          ]
        },
        "version": {
          "type": "string",
          "description": "The complete [SemVer](https://semver.org/) version string.\n\nIt MUST follow the [Semantic Versioning 2.0.0](https://semver.org/) standard.\nIt SHOULD be changed if the ORD information or referenced resource definitions changed.\nIt SHOULD express minor and patch changes that don't lead to incompatible changes.\n\nWhen the `version` major version changes, the [ORD ID](#ord-id) `<majorVersion>` fragment MUST be updated to be identical.\nIn case that a resource definition file also contains a version number (e.g. [OpenAPI `info`.`version`](https://swagger.io/specification/#info-object)), it MUST be equal with the resource `version` to avoid inconsistencies.\n\nThe general [Version and Lifecycle](../index.md#version-and-lifecycle) flow MUST be followed.\n\nNote: A change is only relevant for a version increment, if it affects the ORD resource or ORD taxonomy directly.\nFor example: If a resource within a `Package` changes, but the package itself did not, the package version does not need to be incremented.",
          "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
          "examples": [
            "1.2.3",
            "1.0.0-alpha.1"
          ]
        },
        "isRuntimeExtensible": {
          "type": "boolean",
          "description": "Indicates if the share definition can be extended at runtime\n\nIf set to true, then LOBs can provide dynamic share definitions at runtime to extend the static version of the definitions, for example to add more tables to share.",
          "default": false
        },
        "hdlfsSchemas": {
          "type": "array",
          "description": "Hdlfs schemas included in this share",
          "items": {
            "$ref": "#/definitions/HdlfsSchema"
          },
          "minItems": 1
        },
        "extensible": {
          "type": "object",
          "title": "extensible",
          "additionalProperties": false,
          "properties": {
            "supported": {
              "type": "string",
              "enum": [
                "no",
                "manual",
                "automatic"
              ]
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "supported"
          ],
          "anyOf": [
            {
              "properties": {
                "supported": {
                  "const": "manual"
                }
              },
              "required": [
                "description"
              ]
            },
            {
              "properties": {
                "supported": {
                  "const": "automatic"
                }
              },
              "required": [
                "description"
              ]
            }
          ]
        }
      },
      "required": [
        "name",
        "namespace",
        "title",
        "shortDescription",
        "description",
        "version",
        "hdlfsSchemas",
        "extensible"
      ]
    }
  }
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/foundationobjects/OrganizationalStructure_1.0.0.json
{
   "name": "OrganizationalStructure",
   "namespace": "sap.sf.foundationobjects",
   "title": "OrganizationalStructure",
   "shortDescription": "Org structure refers to org and reporting structure in a company.",
   "description": "Organization structure refers to organizational and reporting structures in a company.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "OrganizationalStructure",
         "shareTables": [
            {
               "name": "businessUnit",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "businessUnit_businessUnitTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "businessUnit_businessUnitText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "division_businessUnit",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "division",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "division_divisionTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "division_divisionText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "department_DepartmentApprenticeDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "department",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "department_division",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "department_departmentTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "department_departmentText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/extensibility/Picklist_1.0.0.json
{
   "name": "Picklist",
   "namespace": "sap.sf.extensibility",
   "title": "Picklist",
   "shortDescription": "All refer picklist, its needed in derived data product transform pipeline and data modelling for out- of- the-box content and Insight app",
   "description": "All referenced picklists, its needed in derived data product's transformation pipeline and data modelling for out- of- the-box content and Insight app.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "Picklist",
         "shareTables": [
            {
               "name": "pickList",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "pickList_pickListTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "pickList_pickListValue",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "pickList_pickListValueText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/learning/Course_1.0.0.json
{
   "name": "Course",
   "namespace": "sap.sf.learning",
   "title": "Course",
   "shortDescription": "Includes all information for an item.",
   "description": "Includes all the information for an item[Entity]",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "Course",
         "shareTables": [
            {
               "name": "course_categories",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "course",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "course_courseText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "course_capabilityRating",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/learning/DeliveryMethod_1.0.0.json
{
   "name": "DeliveryMethod",
   "namespace": "sap.sf.learning",
   "title": "DeliveryMethod",
   "shortDescription": "Reference Data that is required in Learning. Delivery Date assumes that all the dependencies are in place.",
   "description": "Reference Data required in Learning.Delivery Date assumes that all dependencies are in place. If this is not the case then Delivery Qtr will be re-determined",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "DeliveryMethod",
         "shareTables": [
            {
               "name": "deliveryMethod",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "deliveryMethod_deliveryMethodText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/workforce/AssignmentAdditionalInformation_1.0.0.json
{
   "name": "AssignmentAdditionalInformation",
   "namespace": "sap.sf.workforce",
   "title": "AssignmentAdditionalInformation",
   "shortDescription": "Additional info of assignment includes details, such as, job relationships.",
   "description": "Additional information of assignment includes details, such as, job relationships.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "AssignmentAdditionalInformation",
         "shareTables": [
            {
               "name": "jobRelationship",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRelationship_jobRelationshipDetailGrid",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRelationship_jobRelationshipDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/foundationobjects/JobStructure_1.0.0.json
{
   "name": "JobStructure",
   "namespace": "sap.sf.foundationobjects",
   "title": "JobStructure",
   "shortDescription": "Job structure refer to info about job classification and job function.",
   "description": "Job structure refers to information about job classication and job function.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "JobStructure",
         "shareTables": [
            {
               "name": "jobClassification_JobClassificationCHL",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationBOL",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationAUS",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationCAN",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationBRA",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationZAF",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationUSA",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationFRA",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationCountry",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationITA",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_JobClassificationGBR",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_jobClassificationTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobClassification_jobClassificationText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobFunction",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobFunction_jobFunctionTimeSlice",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobFunction_jobFunctionText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/recruiting/JobRequisition_1.0.0.json
{
   "name": "JobRequisition",
   "namespace": "sap.sf.recruiting",
   "title": "JobRequisition",
   "shortDescription": "Data product that helps track job openings and also manage key details to streamline hiring, ensure compliance, and optimize workforce planning in an ATS.",
   "description": "Tracks job openings, managing key details to streamline hiring, ensure compliance, and optimize workforce planning in an ATS.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "JobRequisition",
         "shareTables": [
            {
               "name": "jobRequisition",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_locationItem",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_currencyData",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_operator",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_operatorTeam",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_localizedText",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_jobReqPostings",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_Skills",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_statusAudit",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "jobRequisition_skill",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}

=== SlimShady1414/AdhiCollibraTest/fos_dpd/shares/sap/sf/workforce/WorkforcePerson_1.0.0.json
{
   "name": "WorkforcePerson",
   "namespace": "sap.sf.workforce",
   "title": "WorkforcePerson",
   "shortDescription": "Workforce person contains data that refers to a person and their employment details.",
   "description": "Workforce person data refers to a person and their employment details. Workforce person data includes personal information,biographical information, address, contact information, national ID, social account, country/region-specific information, and employment details such as assignments, job details, and global assignment information.",
   "version": "1.0.0",
   "extensible": {
      "supported": "automatic",
      "description": "Extensions to the model are automatically integrated in the API"
   },
   "hdlfsSchemas": [
      {
         "name": "WorkforcePerson",
         "shareTables": [
            {
               "name": "person_personalDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "person_assignment",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "person",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "person_biographicalLocDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "person_biographicalDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "person_nationalId",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "person_globalDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "assignment_assignmentDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "assignment",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "assignment_primaryAssignment",
               "version": "1.0.0",
               "medallionLayer": "silver"
            },
            {
               "name": "assignment_jobDetail",
               "version": "1.0.0",
               "medallionLayer": "silver"
            }
         ]
      }
   ]
}
